name: release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Create release
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@a37ac6e4f6449ce8b3f7607e4d97d0146028dc0b # v4
        id: release
        with:
          token: ${{ secrets.RELEASE_GITHUB_TOKEN }}

  publish:
    name: Publish to npm (fake)
    runs-on: ubuntu-latest
    needs: release
    if: ${{ needs.release.outputs.releases_created == 'true'  }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile
      - name: Configure npm user
        run: npm config set "//registry.npmjs.org/:_authToken=${NPM_TOKEN}"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
#      - run: pnpm -r publish --access public
